/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppUploadRouteRouteImport } from './routes/app/upload/route'
import { Route as AppProfileRouteRouteImport } from './routes/app/profile/route'
import { Route as AppWatchIndexRouteImport } from './routes/app/watch/index'
import { Route as AppUploadIndexRouteImport } from './routes/app/upload/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppBrowserIndexRouteImport } from './routes/app/browser/index'
import { Route as AppUploadVideoidRouteImport } from './routes/app/upload/$videoid'
import { Route as AppProfileVideosRouteImport } from './routes/app/profile/videos'
import { Route as AppProfileSavedRouteImport } from './routes/app/profile/saved'
import { Route as AppWatchVideoidIndexRouteImport } from './routes/app/watch/$videoid/index'
import { Route as AppActorActorIdIndexRouteImport } from './routes/app/actor/$actorId/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUploadRouteRoute = AppUploadRouteRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWatchIndexRoute = AppWatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUploadIndexRoute = AppUploadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUploadRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppBrowserIndexRoute = AppBrowserIndexRouteImport.update({
  id: '/browser/',
  path: '/browser/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUploadVideoidRoute = AppUploadVideoidRouteImport.update({
  id: '/$videoid',
  path: '/$videoid',
  getParentRoute: () => AppUploadRouteRoute,
} as any)
const AppProfileVideosRoute = AppProfileVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppProfileSavedRoute = AppProfileSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppWatchVideoidIndexRoute = AppWatchVideoidIndexRouteImport.update({
  id: '/watch/$videoid/',
  path: '/watch/$videoid/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActorActorIdIndexRoute = AppActorActorIdIndexRouteImport.update({
  id: '/actor/$actorId/',
  path: '/actor/$actorId/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/app/profile': typeof AppProfileRouteRouteWithChildren
  '/app/upload': typeof AppUploadRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/profile/saved': typeof AppProfileSavedRoute
  '/app/profile/videos': typeof AppProfileVideosRoute
  '/app/upload/$videoid': typeof AppUploadVideoidRoute
  '/app/browser/': typeof AppBrowserIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/upload/': typeof AppUploadIndexRoute
  '/app/watch/': typeof AppWatchIndexRoute
  '/app/actor/$actorId/': typeof AppActorActorIdIndexRoute
  '/app/watch/$videoid/': typeof AppWatchVideoidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app': typeof AppIndexRoute
  '/app/profile/saved': typeof AppProfileSavedRoute
  '/app/profile/videos': typeof AppProfileVideosRoute
  '/app/upload/$videoid': typeof AppUploadVideoidRoute
  '/app/browser': typeof AppBrowserIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/upload': typeof AppUploadIndexRoute
  '/app/watch': typeof AppWatchIndexRoute
  '/app/actor/$actorId': typeof AppActorActorIdIndexRoute
  '/app/watch/$videoid': typeof AppWatchVideoidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/app/profile': typeof AppProfileRouteRouteWithChildren
  '/app/upload': typeof AppUploadRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/profile/saved': typeof AppProfileSavedRoute
  '/app/profile/videos': typeof AppProfileVideosRoute
  '/app/upload/$videoid': typeof AppUploadVideoidRoute
  '/app/browser/': typeof AppBrowserIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/upload/': typeof AppUploadIndexRoute
  '/app/watch/': typeof AppWatchIndexRoute
  '/app/actor/$actorId/': typeof AppActorActorIdIndexRoute
  '/app/watch/$videoid/': typeof AppWatchVideoidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/about'
    | '/test'
    | '/app/profile'
    | '/app/upload'
    | '/auth/login'
    | '/auth/sign-up'
    | '/app/'
    | '/app/profile/saved'
    | '/app/profile/videos'
    | '/app/upload/$videoid'
    | '/app/browser/'
    | '/app/profile/'
    | '/app/upload/'
    | '/app/watch/'
    | '/app/actor/$actorId/'
    | '/app/watch/$videoid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/test'
    | '/auth/login'
    | '/auth/sign-up'
    | '/app'
    | '/app/profile/saved'
    | '/app/profile/videos'
    | '/app/upload/$videoid'
    | '/app/browser'
    | '/app/profile'
    | '/app/upload'
    | '/app/watch'
    | '/app/actor/$actorId'
    | '/app/watch/$videoid'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/about'
    | '/test'
    | '/app/profile'
    | '/app/upload'
    | '/auth/login'
    | '/auth/sign-up'
    | '/app/'
    | '/app/profile/saved'
    | '/app/profile/videos'
    | '/app/upload/$videoid'
    | '/app/browser/'
    | '/app/profile/'
    | '/app/upload/'
    | '/app/watch/'
    | '/app/actor/$actorId/'
    | '/app/watch/$videoid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/watch/': {
      id: '/app/watch/'
      path: '/watch'
      fullPath: '/app/watch/'
      preLoaderRoute: typeof AppWatchIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/upload/': {
      id: '/app/upload/'
      path: '/'
      fullPath: '/app/upload/'
      preLoaderRoute: typeof AppUploadIndexRouteImport
      parentRoute: typeof AppUploadRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/app/browser/': {
      id: '/app/browser/'
      path: '/browser'
      fullPath: '/app/browser/'
      preLoaderRoute: typeof AppBrowserIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/upload/$videoid': {
      id: '/app/upload/$videoid'
      path: '/$videoid'
      fullPath: '/app/upload/$videoid'
      preLoaderRoute: typeof AppUploadVideoidRouteImport
      parentRoute: typeof AppUploadRouteRoute
    }
    '/app/profile/videos': {
      id: '/app/profile/videos'
      path: '/videos'
      fullPath: '/app/profile/videos'
      preLoaderRoute: typeof AppProfileVideosRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/app/profile/saved': {
      id: '/app/profile/saved'
      path: '/saved'
      fullPath: '/app/profile/saved'
      preLoaderRoute: typeof AppProfileSavedRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/app/watch/$videoid/': {
      id: '/app/watch/$videoid/'
      path: '/watch/$videoid'
      fullPath: '/app/watch/$videoid/'
      preLoaderRoute: typeof AppWatchVideoidIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/actor/$actorId/': {
      id: '/app/actor/$actorId/'
      path: '/actor/$actorId'
      fullPath: '/app/actor/$actorId/'
      preLoaderRoute: typeof AppActorActorIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppProfileRouteRouteChildren {
  AppProfileSavedRoute: typeof AppProfileSavedRoute
  AppProfileVideosRoute: typeof AppProfileVideosRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteRouteChildren: AppProfileRouteRouteChildren = {
  AppProfileSavedRoute: AppProfileSavedRoute,
  AppProfileVideosRoute: AppProfileVideosRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteRouteWithChildren = AppProfileRouteRoute._addFileChildren(
  AppProfileRouteRouteChildren,
)

interface AppUploadRouteRouteChildren {
  AppUploadVideoidRoute: typeof AppUploadVideoidRoute
  AppUploadIndexRoute: typeof AppUploadIndexRoute
}

const AppUploadRouteRouteChildren: AppUploadRouteRouteChildren = {
  AppUploadVideoidRoute: AppUploadVideoidRoute,
  AppUploadIndexRoute: AppUploadIndexRoute,
}

const AppUploadRouteRouteWithChildren = AppUploadRouteRoute._addFileChildren(
  AppUploadRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppProfileRouteRoute: typeof AppProfileRouteRouteWithChildren
  AppUploadRouteRoute: typeof AppUploadRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppBrowserIndexRoute: typeof AppBrowserIndexRoute
  AppWatchIndexRoute: typeof AppWatchIndexRoute
  AppActorActorIdIndexRoute: typeof AppActorActorIdIndexRoute
  AppWatchVideoidIndexRoute: typeof AppWatchVideoidIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRouteRoute: AppProfileRouteRouteWithChildren,
  AppUploadRouteRoute: AppUploadRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppBrowserIndexRoute: AppBrowserIndexRoute,
  AppWatchIndexRoute: AppWatchIndexRoute,
  AppActorActorIdIndexRoute: AppActorActorIdIndexRoute,
  AppWatchVideoidIndexRoute: AppWatchVideoidIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
